# Generated by Django 3.1.4 on 2020-12-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20201203_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='cheese_pizza.png', upload_to='pizzas'),
        ),
    ]
